services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=asdqwe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  broker:
    image: confluentinc/cp-kafka:latest
    # Prod setup: 4 broker, 3 replication per partition, 8-15 partitions 
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  api:
    container_name: api
    ports:
      - "3500:3500"
    image: kafka/api
    environment:
      PRODUCER_BOOTSTRAP_SERVERS: 'broker:9092'
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:3500/healthz && exit 0 || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 100
      start_period: 30s
    depends_on:
      broker:
        condition: service_started
      postgres:
        condition: service_started
      dbmigrator:
        condition: service_started
  dbmigrator:
    container_name: migrator
    image: kafka/api
    depends_on:
      postgres:
        condition: service_started
    command:
      - -cp
      - api-0.0.1-SNAPSHOT-jar-with-dependencies.jar
      - com.kafka.api.DBMigrator
      - --spring.jpa.hibernate.ddl-auto=update
